name: 🦀 Push to main

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    uses: ./.github/workflows/lint.yml

  build:
    needs: lint
    name: Build
    uses: ./.github/workflows/build.yml

  release-cargo:
    needs: build
    name: Release Cargo
    secrets: inherit
    uses: ./.github/workflows/release_cargo.yml

  release-npm:
    needs: build
    name: Release NPM
    secrets: inherit
    uses: ./.github/workflows/release_npm.yml
